version: '3.6'
services:
  weather-api-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - weather-api
  weather-api-server:
    container_name: weather-api-server
    build: .
    environment:
      - "PROFILE=${PROFILE}"
      - "DB_USERNAME=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_HOST=jdbc:mysql://weather-api-db:3306/weather?autoReconnect=true&useSSL=false"
    ports:
      - "8080:8080"
    depends_on:
      - weather-api-db
    networks:
      - weather-api
volumes:
  db-volume:
networks:
  weather-api: