version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: amazoncorretto:11-alpine-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies, run tests, and collect coverage
          command: gradle build
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build